name: Go
on: [push]
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
        cache-dependency-path: go.mod
      id: go
    - name: Modules
      run: go get -v -t -d ./...
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
